### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by joshcangit** [LambdAurora/MCPatcherPatcher#10]
Don't know how to use this as a _Standalone Jar_.
Not sure how to "output the converted files".

Can't find but does it have a GUI?
Is there a CLI? It doesn't seem to have one.

I am trying to convert [Better dogs resource pack](https://www.curseforge.com/minecraft/texture-packs/better-dogs), an Optifine/MCPatcher-based resource pack (containing emissive.properties), to be used with Varied Mod Textures mod.

Will it convert? If so, exactly how to do it. I don't see any explanation in the Readme. Please help.

**Comment by LambdAurora** [comment]
I don't think it can be used as a standalone JAR yet as the build target doesn't put the files to indicate the main class, but it will be CLI, and maybe a GUI.

We can't guarantee at the moment that VMT format conversion works as it's still WIP, but you can try as a fabric mod, it will convert at runtime the mod.

**Comment by joshcangit** [comment]
Tried it just now but it didn't seem to be loaded.

**Comment by DragonEggBedrockBreaking** [comment]
It can be used as a standalone app now (GUI), so should this be closed?
