### ISSUE TITLE
[Fabric Skyboxes] Certain types of skyboxes don't render and appear incorrectly, usually appearing on incorrect times 

### ISSUE THREAD

**Issue by Snivine** [LambdAurora/MCPatcherPatcher#11]
**Expected Behaviour:**

Skyboxes work in the correct time set

**Actualy Behaviour:**

Skyboxes don't appear in the correct time set or don't appear at all

**Resource Pack Used: https://www.curseforge.com/minecraft/texture-packs/newdefaultplus**

**Screenshots:**

MCPatcherPatcher + Fabric Skyboxes: 
![2020-11-09_16 56 41](https://user-images.githubusercontent.com/72054019/98641741-dc18af00-22f1-11eb-8aa2-0a48111472ba.png)

Optifine:
![2020-11-10_01 29 37](https://user-images.githubusercontent.com/72054019/98643371-8b568580-22f4-11eb-9149-4b4c3b78c88a.png)

**Extra notes:**

1. I'm doing this here because I'm certain that is a conversion issue, since I don't know how to convert them manually I'm thinking that it's MCPP faults due to not converting it correctly
2. If you redirect me to Fabric Skyboxes I'll go post the issue there
3. For having them on the same ground, they're both running on Fabric Loader version: 0.10.6+build.214 with the same mods in the same states and possitions

**Comment by Snivine** [comment]
After doing some testing it seems that it is indeed MCPatcherPatcher

MCPatcherPatcher translates the Blend option "Add" to false, which is incorrect, it should be true

**Comment by Snivine** [comment]
it's actually more complicated than that, add doesn't work perfectly so that's an issue

**Comment by FlashyReese** [comment]
Unfortunately there isn't much I can do aside from setting FabricSkyboxes' blend to true. If clouds aren't playing well with blending it's FabricSkyboxes' end that needs a patch. I have spoke to the dev about it, he said he will look into when he has time.
