### ISSUE TITLE
Support CBT and Chime

### ISSUE THREAD

**Issue by timelady-victorious** [LambdAurora/MCPatcherPatcher#16]
Theses are two mods that replace CTM and CIT.

**Comment by LambdAurora** [comment]
CBT reads OptiFine format...

**Comment by LucilleTea** [comment]
The Chime dev is working on her own converter (which can't be 100% comprehensive but will work for simple cases).
I think a converter may not belong here in that case.

**Comment by timelady-victorious** [comment]
@LambdAurora  oops, I am silly, sorry. (Also CBT now crashes on 1.16.4, which is sad). Nice to hear CIT - Chime is being worked on
