### ISSUE TITLE
feature request: chime compatibility

### ISSUE THREAD

**Issue by itsbumble** [LambdAurora/MCPatcherPatcher#17]
I heard there's a mod called Chime that adds CIT support but in a different format. it would be nice to see mc patcher patcher convert optifine cit packs into chime cit packs (I haven't used this mod and don't 100% know how it works, correct me if this isn't possible)

**Comment by DragonEggBedrockBreaking** [comment]
> I heard there's a mod called Chime that adds CIT support but in a different format. it would be nice to see mc patcher patcher convert optifine cit packs into chime cit packs (I haven't used this mod and don't 100% know how it works, correct me if this isn't possible)

There is already a WIP converter by the person who created Chime. Here it is: https://github.com/emilyalexandra/chime-converter

**Comment by itsbumble** [comment]
oh wow awesome

**Comment by DragonEggBedrockBreaking** [comment]
> oh wow awesome

Maybe you should close this?

**Comment by itsbumble** [comment]
> > oh wow awesome
> 
> Maybe you should close this?

oh yeah sorry forgot to close it
